# Generated by Django 6.0.3 on 2026-03-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticasusuariotrivia',
            name='usuario',
        ),
        migrations.RemoveIndex(
            model_name='historialjuegotrivia',
            name='games_histo_fecha_j_ff5382_idx',
        ),
        migrations.RemoveIndex(
            model_name='historialjuegotrivia',
            name='games_histo_usuario_189dec_idx',
        ),
        migrations.RemoveIndex(
            model_name='historialjuegotrivia',
            name='games_histo_categor_19e619_idx',
        ),
        migrations.DeleteModel(
            name='EstadisticasUsuarioTrivia',
        ),
        migrations.DeleteModel(
            name='HistorialJuegoTrivia',
        ),
    ]
