# Generated by Django 6.0.2 on 2026-02-13 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='rutas_imagenes/')),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longitud (km)')),
                ('coordenadas_ruta', models.JSONField(blank=True, null=True, verbose_name='Coordenadas de la Ruta')),
                ('nombre_ruta', models.CharField(max_length=255, verbose_name='Nombre de la Ruta')),
                ('dificultad', models.CharField(choices=[('FACIL', 'Fácil'), ('MODERADO', 'Moderado'), ('DIFICIL', 'Difícil'), ('EXTREMO', 'Extremo')], default='MODERADO', max_length=50, verbose_name='Dificultad')),
                ('duracion_estimada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duración Estimada')),
                ('ubicacion_inicio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación de Inicio')),
                ('ubicacion_fin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación de Fin')),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación General')),
                ('puntos_interes', models.TextField(blank=True, null=True, verbose_name='Puntos de Interés')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['nombre_ruta'],
            },
        ),
        migrations.CreateModel(
            name='UserRutaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorita_por_usuarios', to='routes.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritas_intermedias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruta Favorita de Usuario',
                'verbose_name_plural': 'Rutas Favoritas de Usuarios',
                'unique_together': {('usuario', 'ruta')},
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuarios_favoritos',
            field=models.ManyToManyField(related_name='rutas_favoritas', through='routes.UserRutaFavorita', to=settings.AUTH_USER_MODEL, verbose_name='Marcada como Favorita por'),
        ),
    ]
