# Generated by Django 6.0.3 on 2026-03-21 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_ruta_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutarecorrida',
            options={'ordering': ['-fecha'], 'verbose_name': 'Ruta Recorrida', 'verbose_name_plural': 'Rutas Recorridas'},
        ),
        migrations.AddField(
            model_name='rutarecorrida',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='rutarecorrida',
            name='puntos_ganados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rutarecorrida',
            name='tiempo_segundos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rutarecorrida',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to='routes.ruta'),
        ),
        migrations.AlterField(
            model_name='rutarecorrida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorridos', to=settings.AUTH_USER_MODEL),
        ),
    ]
