# Generated by Django 6.0.3 on 2026-03-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_alter_rutarecorrida_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='altura_promedio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Altura promedio (m.s.n.m)'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Recomendaciones'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipo_terreno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de terreno'),
        ),
    ]
