# Generated by Django 6.0.3 on 2026-03-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_notificacion'),
        ('routes', '0003_alter_ruta_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_publicacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='comentario',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.ruta'),
        ),
    ]
