# Generated by Django 6.0.2 on 2026-02-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_ruta_imagen_rutarecorrida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='rutas/'),
        ),
    ]
