# Generated by Django 6.0.2 on 2026-02-13 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_puntos', models.IntegerField(default=0)),
                ('Puntos_mensuales', models.IntegerField(default=0)),
                ('puntos_semanales', models.IntegerField(default=0)),
                ('distancia_total_km', models.FloatField(default=0)),
                ('dias_activos', models.IntegerField(default=0)),
                ('ultima_actividad', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadas_recorrido', models.JSONField(blank=True, null=True, verbose_name='Coordenadas del Recorrido')),
                ('duracion_segundos', models.IntegerField(default=0, verbose_name='Duración en Segundos')),
                ('titulo', models.CharField(max_length=100)),
                ('localizacion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('distancia_km', models.FloatField()),
                ('duration_horas', models.FloatField()),
                ('puntos_caminata', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='walks/')),
                ('en_progreso', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankingSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('semana_fin', models.DateField()),
                ('puntos_semana', models.IntegerField()),
                ('distancia_semana', models.FloatField()),
                ('posicion', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['posicion'],
                'unique_together': {('usuario', 'semana_inicio')},
            },
        ),
    ]
