# Generated by Django 6.0.2 on 2026-02-13 20:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasUsuarioTrivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_juegos', models.IntegerField(default=0, verbose_name='Total de Juegos')),
                ('total_puntos', models.IntegerField(default=0, verbose_name='Puntos Totales Acumulados')),
                ('mejor_puntaje', models.IntegerField(default=0, verbose_name='Mejor Puntaje')),
                ('categoria_favorita', models.CharField(blank=True, help_text='Categoría más jugada', max_length=20, null=True, verbose_name='Categoría Favorita')),
                ('total_correctas', models.IntegerField(default=0, verbose_name='Total Respuestas Correctas')),
                ('total_incorrectas', models.IntegerField(default=0, verbose_name='Total Respuestas Incorrectas')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_trivia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estadística de Usuario',
                'verbose_name_plural': 'Estadísticas de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='HistorialJuegoTrivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('rutas', 'Rutas'), ('equipo', 'Equipo'), ('seguridad', 'Seguridad'), ('flora-fauna', 'Flora y Fauna'), ('tecnicas', 'Técnicas'), ('lugares', 'Lugares Icónicos')], help_text='Categoría de preguntas jugada', max_length=20, verbose_name='Categoría/Nivel')),
                ('puntos', models.IntegerField(default=0, help_text='Total de puntos (máximo 500 - 5 preguntas x 100 pts)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='Puntos Obtenidos')),
                ('respuestas_correctas', models.IntegerField(default=0, help_text='Número de respuestas correctas', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Respuestas Correctas')),
                ('respuestas_incorrectas', models.IntegerField(default=0, help_text='Número de respuestas incorrectas', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Respuestas Incorrectas')),
                ('fecha_juego', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se completó el juego', verbose_name='Fecha y Hora del Juego')),
                ('duracion_segundos', models.IntegerField(blank=True, help_text='Tiempo que tardó en completar el juego', null=True, verbose_name='Duración (segundos)')),
                ('usuario', models.ForeignKey(help_text='Usuario que jugó la trivia', on_delete=django.db.models.deletion.CASCADE, related_name='juegos_trivia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Juego',
                'verbose_name_plural': 'Historial de Juegos',
                'ordering': ['-fecha_juego'],
                'indexes': [models.Index(fields=['-fecha_juego'], name='games_histo_fecha_j_ff5382_idx'), models.Index(fields=['usuario', '-fecha_juego'], name='games_histo_usuario_189dec_idx'), models.Index(fields=['categoria'], name='games_histo_categor_19e619_idx')],
            },
        ),
    ]
