# Generated by Django 6.0.3 on 2026-03-08 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMapaRoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('normal', 'Normal'), ('dificil', 'Difícil')], max_length=10, verbose_name='Dificultad')),
                ('imagen_mapa', models.CharField(blank=True, help_text='Nombre del archivo de imagen resuelto', max_length=255, null=True, verbose_name='Imagen del mapa')),
                ('duracion_segundos', models.IntegerField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('pistas_usadas', models.IntegerField(default=0, verbose_name='Pistas usadas')),
                ('fecha_juego', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos_mapa_roto', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial Mapa Roto',
                'verbose_name_plural': 'Historial Mapa Roto',
                'ordering': ['-fecha_juego'],
            },
        ),
    ]
