# Generated by Django 6.0.3 on 2026-03-04 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_ruta_imagen'),
        ('users', '0002_alter_usuariopersonalizado_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('maps_url', models.URLField(blank=True, null=True, verbose_name='Link Google Maps')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje adicional')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('FALSA', 'Falsa alarma')], default='PENDIENTE', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('notas_admin', models.TextField(blank=True, null=True, verbose_name='Notas del admin')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendida por')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.ruta', verbose_name='Ruta activa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_sos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Alerta SOS',
                'verbose_name_plural': 'Alertas SOS',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
